INSERT INTO PLAYER_ACCOUNT(PLAYER_ID, PLAYER_NAME, CURRENT_BALANCE) VALUES(1,'Anders', 10000.0);
INSERT INTO PLAYER_ACCOUNT(PLAYER_ID, PLAYER_NAME, CURRENT_BALANCE) VALUES(2,'Solvig', 0.0);
INSERT INTO PLAYER_ACCOUNT(PLAYER_ID, PLAYER_NAME, CURRENT_BALANCE) VALUES(3,'Sigfrid', 10.0);
INSERT INTO PLAYER_ACCOUNT(PLAYER_ID, PLAYER_NAME, CURRENT_BALANCE) VALUES(4, 'Eric', 100.0);
INSERT INTO PLAYER_ACCOUNT(PLAYER_ID, PLAYER_NAME, CURRENT_BALANCE) VALUES(5,'Edvin', 50.0);
SELECT * FROM PLAYER_ACCOUNT;